// console.log("hello")
const con = document.getElementById('container')
const root = ReactDOM.createRoot(con)
// const h2 = React.createElement('h2', { style: { color: 'red' } }, "welcome to React")
const h1 = React.createElement('h1', {style:{backgroundColor:'red'}}, "Abes Engineering College")
const img=React.createElement('img',{src:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7KTIHGBfCzIoshUilqSGBnFhxC8XTo5hlLX__d1g1XA&s',style:{height:'300px',width:'300px'}})
const fullname=React.createElement('h2', {}, "Name: Nikhil Kushwaha")
const roll=React.createElement('h2', {}, "RollNo: 2400321530135")
const branch=React.createElement('h2', {}, "Branch: CSE-AIML")
const div = React.createElement('div', { style: { border: '4px solid black', width: '600px',margin:'auto',} }, img,h1,fullname,roll,branch)
root.render(div)
